// Copies the design-v2 shell of the site into the Ghost blog theme (repo base-xtech/basex-ghost), so the blog
// looks and sends leads exactly like the site. Run after `npm run build`:
//   node scripts/ghost-shell.mjs [path/to/basex-ghost]   (default ../basex-ghost)
// Writes: partials/v2/{header,nav,rail,form,footer}.hbs, assets/v2/{v2.css,v2.js,fonts/*}. Nothing else in the theme.
import fs from 'node:fs';
import path from 'node:path';
import { parse } from 'node-html-parser';
import { build } from 'esbuild';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const theme = path.resolve(process.argv[2] || path.join(root, '..', 'basex-ghost'));
const site = 'https://base-xtech.com';
const dist = path.join(root, 'dist');
if (!fs.existsSync(path.join(dist, 'index.html'))) throw new Error('run npm run build first');
if (!fs.existsSync(path.join(theme, 'package.json'))) throw new Error(`not a theme: ${theme}`);

const out = (rel, data) => { const p = path.join(theme, rel); fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, data); console.log('wrote', rel); };
const note = '{{!-- Generated by basextech-website/scripts/ghost-shell.mjs from the site build. Do not edit here. --}}\n';

// ---- HTML: header, mobile menu, modal, footer from the EN home page (links made absolute to the main site)
const doc = parse(fs.readFileSync(path.join(dist, 'index.html'), 'utf8'));
const absolute = (html) => html
  .replace(/(href|src)="\/(?!\/)/g, `$1="${site}/`)
  .replace(/srcset="([^"]*)"/g, (m, v) => `srcset="${v.replace(/(^|,\s*)\/(?!\/)/g, `$1${site}/`)}"`);
const hbsSafe = (html) => html.replace(/\{\{/g, '\\{{');
const pick = (sel) => { const el = doc.querySelector(sel); if (!el) throw new Error(`missing ${sel}`); return el; };

const header = pick('header.v2-header');
// the blog is part of "Insights": mark it current; the language menu points at the three home pages (blog is EN only)
let headerHtml = absolute(header.outerHTML)
  .replace(new RegExp(`href="${site}/blog/"`, 'g'), `href="${site}/blog/" aria-current="page"`);
out('partials/v2/header.hbs', note + hbsSafe(headerHtml) + '\n');
out('partials/v2/nav.hbs', note + hbsSafe(absolute(pick('#v2-mnav').outerHTML)) + '\n');
out('partials/v2/rail.hbs', note + pick('nav.v2-rail').outerHTML + '\n'); // left column with section dots (desktop)
out('partials/v2/form.hbs', note + hbsSafe(absolute(pick('.v2-modal').outerHTML)) + '\n');
out('partials/v2/footer.hbs', note + hbsSafe(absolute(pick('footer.v2-footer').outerHTML)) + '\n');

// ---- CSS: the v2 stylesheet; fonts copied into the theme, images from the main site
const cssFile = fs.readdirSync(path.join(dist, 'assets/css')).find((f) => /^v2-.*\.css$/.test(f));
let css = fs.readFileSync(path.join(dist, 'assets/css', cssFile), 'utf8');
const fonts = new Set();
css = css.replace(/url\((['"]?)\/fonts\/([^)'"]+)\1\)/g, (m, q, f) => { fonts.add(f); return `url(fonts/${f})`; })
  .replace(/url\((['"]?)\/(?!\/)([^)'"]+)\1\)/g, (m, q, p) => `url(${site}/${p})`)
  // the Ghost theme (Source) sets html { font-size: 62.5% }; the site's rem values assume 16px
  .replace(/(\d*\.?\d+)rem\b/g, (m, n) => `${+(n * 16).toFixed(3)}px`);
out('assets/v2/v2.css', `/* Generated by basextech-website/scripts/ghost-shell.mjs from ${cssFile}. Do not edit here. */\n${css}`);
for (const f of fonts) {
  const src = path.join(dist, 'fonts', f);
  if (fs.existsSync(src)) { fs.mkdirSync(path.join(theme, 'assets/v2/fonts'), { recursive: true }); fs.copyFileSync(src, path.join(theme, 'assets/v2/fonts', f)); }
  else console.warn('font not found', f);
}
console.log('fonts', [...fonts].join(', '));

// ---- JS: drawers + lead form + v2 interactions; real leads only from the live domain
await build({
  entryPoints: [path.join(root, 'src/blog/blog.js')],
  bundle: true, minify: true, format: 'iife', target: 'es2019',
  define: { __DEPLOY_ENV__: 'window.__BX_ENV__' },
  outfile: path.join(theme, 'assets/v2/v2.js'),
  banner: { js: "/* Generated by basextech-website/scripts/ghost-shell.mjs (src/blog/blog.js). Do not edit here. */\nwindow.__BX_ENV__ = location.hostname === 'base-xtech.com' ? 'prod' : 'dev';" },
});
console.log('wrote assets/v2/v2.js');
